### ISSUE TITLE
Installing the Addons

### ISSUE THREAD

**Issue by ChallengerI** [Pikachu7/FreeBuddy#10]
It crashes the loader when installing from the local addon

**Comment by Pikachu7** [comment]
1) Download our repo and extract from archive.
2) Go to Installer/Updater section and install/update the files. [WHILE EB LOADER IS OPEN]
3) Then go to "Randomizer" tab and select .csproj files and press randomize.
4) Install the addons from Local Addon section in EloBuddy Loader.
Have Fun !
