### ISSUE TITLE
Failed to install

### ISSUE THREAD

**Issue by orkenaga** [Pikachu7/FreeBuddy#3]
Hocam bu hatayı alıyorum, tespitime göre elo buddy binary kısmına inen evadeinc ve diğer 2 addonun dll dosyalarını siliyor böylelikle inmiyor dosya

**Comment by Pikachu7** [comment]
Dosyaları https://github.com/Pikachu7/FreeBuddy/archive/master.zip buradan indirip Yerel olarak kurunuz.

**Comment by orkenaga** [comment]
Onuda denedim bu seferde elobuddy crash
