### ISSUE TITLE
Evade IC Crashs

### ISSUE THREAD

**Issue by X10NLUN1X** [Pikachu7/FreeBuddy#5]
After they Updated the Core, your Addon fix EvadeIC is crashing.
you did a great job there. Keep it running  <3

**Comment by ale3x21** [comment]
Same for me

**Comment by zeksht** [comment]
I have the same problem with EvadeIC, BeastyRiven and MasterTheEnemy.

**Comment by Pikachu7** [comment]
Hello FreeBuddy community,
we will fix asap.
please wait.
Regards Pikachu7

**Comment by Pikachu7** [comment]
Updated.

**Comment by ale3x21** [comment]
Ty sir
