### ISSUE TITLE
nothing is injecting

### ISSUE THREAD

**Issue by X10NLUN1X** [Pikachu7/FreeBuddy#6]
Thank you for your hard work. I kinda love the new Loader <3
but nothing is injecting.

Injection Console Error : http://puu.sh/rxRGL/dd4ee709cb.png
Master the Enemy Compille Error : http://puu.sh/rxRsM/831c91212c.png

everything done as in Loader Description

Edit: Same for Riven  http://puu.sh/rxT2n/0c19bf8c8d.png

**Comment by zeksht** [comment]
I have the same problem.

**Comment by Pikachu7** [comment]
Hi ,
we will fix tomorrow.
Regards Pikachu7

**Comment by Pikachu7** [comment]
SoonTM
http://puu.sh/rzEsr/8e2d8abb9b.jpg

**Comment by rexyrexy** [comment]
Updated and fixed use new loader :
https://github.com/Pikachu7/FreeBuddy/raw/master/FreeBuddy.exe
