### ISSUE TITLE
NA

### ISSUE THREAD

**Issue by flph** [Pikachu7/FreeBuddy#7]
Hi. I like your work and im intrested about the dll thing. Do you decompile or decrypt the creative generated exe or there is anything you can teach me to do some exploration and intro in this area? Thanks budy.

**Comment by NoobPolice** [comment]
You need to decompile the Dll file. 
For example with dotpeek. 
After that you fix the stuff and recompiling it.

**Comment by flph** [comment]
But what dll file ? Its an exe.

**Comment by X10NLUN1X** [comment]
i think he mean http://puu.sh/ryQob/df0ef3bee9.png

**Comment by flph** [comment]
But that one is anything exe renamed to dll :)

**Comment by flph** [comment]
Ok, i managed to do it, ty for no help :)

**Comment by NoobPolice** [comment]
Anytime again my friend :)
