### ISSUE TITLE
Infinite update loop

### ISSUE THREAD

**Issue by zeksht** [Pikachu7/FreeBuddy#8]
When I open FreeBuddy.exe it starts updating and close the loader, then it just open again and starts updating again.

**Comment by zeksht** [comment]
http://prntscr.com/cql9pl

**Comment by Pikachu7** [comment]
fixed. try again 30 seconds later.
Regards Pikachu7.

**Comment by wegotcha** [comment]
still the same here ^^

**Comment by Pikachu7** [comment]
wait please.
i will fix asap.

**Comment by Pikachu7** [comment]
fixed, try again now.

**Comment by X10NLUN1X** [comment]
Still Opening and closeing for me
